name: zburhop
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010a31'
    - '#ffffdb'
    - '#ff00bc'
    - '#4f4e5c'
    - '#df669f'
  brandStrength: 0.3774034734815359
  lightness: 0.5902079043444246
  saturation: 0.31430931808426976
  rhythmicContrast: 0.0010534273460507393
purpose: []
